if (-not (Test-Path "out")) {
                New-Item -ItemType Directory -Path "out" | Out-Null 
                New-Item -ItemType Directory -Path "out\deck" | Out-Null
                New-Item -ItemType Directory -Path "out\deck\digital" | Out-Null
                New-Item -ItemType Directory -Path "out\deck\physical" | Out-Null
            }
typst compile --format svg leyline-test.typ out/leyline-test.svg
typst compile --format svg raging-bull-slash.typ out/raging-bull-slash.svg
typst compile --format svg raging-bull-right-horn.typ out/raging-bull-right-horn.svg
typst compile --format svg raging-bull-left-horn.typ out/raging-bull-left-horn.svg
typst compile --format svg raging-bull-thunderous-hooves.typ out/raging-bull-thunderous-hooves.svg
typst compile --format svg raging-bull-gore.typ out/raging-bull-gore.svg
typst compile --format svg raging-bull-gallop.typ out/raging-bull-gallop.svg
typst compile --format svg raging-bull-bull-rush.typ out/raging-bull-bull-rush.svg
typst compile --format pdf raging-bull-physical.typ out/deck/digital/raging-bull-digital.pdf
typst compile --format png raging-bull-digital.typ out/deck/physical/raging-bull-digital.png
typst compile --format svg raging-bull-board.typ out/raging-bull-board.svg
typst compile --format svg swarm-loot.typ out/swarm-loot.svg
typst compile --format svg swarm-twisting-vines.typ out/swarm-twisting-vines.svg
typst compile --format svg swarm-root.typ out/swarm-root.svg
typst compile --format svg swarm-toxic-spores.typ out/swarm-toxic-spores.svg
typst compile --format svg swarm-spores.typ out/swarm-spores.svg
typst compile --format svg swarm-harvest.typ out/swarm-harvest.svg
typst compile --format svg swarm-whip.typ out/swarm-whip.svg
typst compile --format svg swarm-blossom.typ out/swarm-blossom.svg
typst compile --format svg swarm-seed.typ out/swarm-seed.svg
typst compile --format pdf swarm-physical.typ out/deck/digital/swarm-digital.pdf
typst compile --format png swarm-digital.typ out/deck/physical/swarm-digital.png
typst compile --format svg swarm-board.typ out/swarm-board.svg
typst compile --format svg dragon-scorch.typ out/dragon-scorch.svg
typst compile --format svg dragon-torch.typ out/dragon-torch.svg
typst compile --format svg dragon-blasting-heat.typ out/dragon-blasting-heat.svg
typst compile --format svg dragon-cough.typ out/dragon-cough.svg
typst compile --format svg dragon-check.typ out/dragon-check.svg
typst compile --format svg dragon-mate.typ out/dragon-mate.svg
typst compile --format svg dragon-tail-swipe.typ out/dragon-tail-swipe.svg
typst compile --format svg dragon-depth-first-breath.typ out/dragon-depth-first-breath.svg
typst compile --format svg dragon-right-breath.typ out/dragon-right-breath.svg
typst compile --format svg dragon-love.typ out/dragon-love.svg
typst compile --format pdf dragon-physical.typ out/deck/digital/dragon-digital.pdf
typst compile --format png dragon-digital.typ out/deck/physical/dragon-digital.png
typst compile --format svg dragon-board.typ out/dragon-board.svg
typst compile --format svg gardener-loot.typ out/gardener-loot.svg
typst compile --format svg gardener-twisting-vines.typ out/gardener-twisting-vines.svg
typst compile --format svg gardener-root.typ out/gardener-root.svg
typst compile --format svg gardener-toxic-spores.typ out/gardener-toxic-spores.svg
typst compile --format svg gardener-spores.typ out/gardener-spores.svg
typst compile --format svg gardener-harvest.typ out/gardener-harvest.svg
typst compile --format svg gardener-whip.typ out/gardener-whip.svg
typst compile --format svg gardener-blossom.typ out/gardener-blossom.svg
typst compile --format svg gardener-seed.typ out/gardener-seed.svg
typst compile --format pdf gardener-physical.typ out/deck/digital/gardener-digital.pdf
typst compile --format png gardener-digital.typ out/deck/physical/gardener-digital.png
typst compile --format svg gardener-board.typ out/gardener-board.svg
typst compile --format svg golem-stalag-might.typ out/golem-stalag-might.svg
typst compile --format svg golem-groundpound.typ out/golem-groundpound.svg
typst compile --format svg golem-rock-throw.typ out/golem-rock-throw.svg
typst compile --format svg golem-cave-in.typ out/golem-cave-in.svg
typst compile --format svg golem-mud-bath.typ out/golem-mud-bath.svg
typst compile --format svg golem-stalag-tight.typ out/golem-stalag-tight.svg
typst compile --format svg golem-quake.typ out/golem-quake.svg
typst compile --format svg golem-rolling-earth.typ out/golem-rolling-earth.svg
typst compile --format svg golem-rock-blast.typ out/golem-rock-blast.svg
typst compile --format pdf golem-physical.typ out/deck/digital/golem-digital.pdf
typst compile --format png golem-digital.typ out/deck/physical/golem-digital.png
typst compile --format svg golem-board.typ out/golem-board.svg
typst compile --format svg cutthroat-slash.typ out/cutthroat-slash.svg
typst compile --format svg cutthroat-eviscerate.typ out/cutthroat-eviscerate.svg
typst compile --format svg cutthroat-cloak.typ out/cutthroat-cloak.svg
typst compile --format pdf cutthroat-physical.typ out/deck/digital/cutthroat-digital.pdf
typst compile --format png cutthroat-digital.typ out/deck/physical/cutthroat-digital.png
typst compile --format svg cutthroat-board.typ cutthroat-board.svg
typst compile --format svg ecclesiarch-heal.typ out/ecclesiarch-heal.svg
typst compile --format svg ecclesiarch-bad-touch.typ out/ecclesiarch-bad-touch.svg
typst compile --format svg ecclesiarch-teleport.typ out/ecclesiarch-teleport.svg
typst compile --format pdf ecclesiarch-physical.typ out/deck/digital/ecclesiarch-digital.pdf
typst compile --format png ecclesiarch-digital.typ out/deck/physical/ecclesiarch-digital.png
typst compile --format svg ecclesiarch-board.typ ecclesiarch-board.svg
typst compile --format svg engine-heal.typ out/engine-heal.svg
typst compile --format svg engine-broadside.typ out/engine-broadside.svg
typst compile --format svg engine-u-turn.typ out/engine-u-turn.svg
typst compile --format pdf engine-physical.typ out/deck/digital/engine-digital.pdf
typst compile --format png engine-digital.typ out/deck/physical/engine-digital.png
typst compile --format svg engine-board.typ engine-board.svg
typst compile --format svg evoker-immolation.typ out/evoker-immolation.svg
typst compile --format svg evoker-cauterize.typ out/evoker-cauterize.svg
typst compile --format svg evoker-death-ray.typ out/evoker-death-ray.svg
typst compile --format pdf evoker-physical.typ out/deck/digital/evoker-digital.pdf
typst compile --format png evoker-digital.typ out/deck/physical/evoker-digital.png
typst compile --format svg evoker-board.typ evoker-board.svg
typst compile --format svg mystic-swapper.typ out/mystic-swapper.svg
typst compile --format svg mystic-hurt.typ out/mystic-hurt.svg
typst compile --format svg mystic-hedgehog.typ out/mystic-hedgehog.svg
typst compile --format svg mystic-yuch.typ out/mystic-yuch.svg
typst compile --format svg mystic-shoot.typ out/mystic-shoot.svg
typst compile --format svg mystic-help.typ out/mystic-help.svg
typst compile --format pdf mystic-physical.typ out/deck/digital/mystic-digital.pdf
typst compile --format png mystic-digital.typ out/deck/physical/mystic-digital.png
typst compile --format svg mystic-board.typ mystic-board.svg
typst compile --format svg saurian-swipe.typ out/saurian-swipe.svg
typst compile --format svg saurian-tail-whip.typ out/saurian-tail-whip.svg
typst compile --format svg saurian-toxic-spines.typ out/saurian-toxic-spines.svg
typst compile --format pdf saurian-physical.typ out/deck/digital/saurian-digital.pdf
typst compile --format png saurian-digital.typ out/deck/physical/saurian-digital.png
typst compile --format svg saurian-board.typ saurian-board.svg
typst compile --format svg stalker-loose.typ out/stalker-loose.svg
typst compile --format svg stalker-scoot-n-shoot.typ out/stalker-scoot-n-shoot.svg
typst compile --format svg stalker-pushing-shot.typ out/stalker-pushing-shot.svg
typst compile --format pdf stalker-physical.typ out/deck/digital/stalker-digital.pdf
typst compile --format png stalker-digital.typ out/deck/physical/stalker-digital.png
typst compile --format svg stalker-board.typ stalker-board.svg
typst compile --format svg vanguard-armor-shatter.typ out/vanguard-armor-shatter.svg
typst compile --format svg vanguard-sword-and-board.typ out/vanguard-sword-and-board.svg
typst compile --format svg vanguard-sacrifice.typ out/vanguard-sacrifice.svg
typst compile --format pdf vanguard-physical.typ out/deck/digital/vanguard-digital.pdf
typst compile --format png vanguard-digital.typ out/deck/physical/vanguard-digital.png
typst compile --format svg vanguard-board.typ vanguard-board.svg
typst compile --format svg draft-fan-of-knives.typ out/draft-fan-of-knives.svg
typst compile --format svg draft-delay.typ out/draft-delay.svg
typst compile --format svg draft-leap-frog.typ out/draft-leap-frog.svg
typst compile --format svg draft-shadows-of-doubt.typ out/draft-shadows-of-doubt.svg
typst compile --format svg draft-ice-cube.typ out/draft-ice-cube.svg
typst compile --format svg draft-tunnel.typ out/draft-tunnel.svg
typst compile --format svg draft-restore.typ out/draft-restore.svg
typst compile --format svg draft-fire-walk.typ out/draft-fire-walk.svg
typst compile --format svg draft-flee.typ out/draft-flee.svg
typst compile --format svg draft-poisonous-cloud.typ out/draft-poisonous-cloud.svg
typst compile --format svg draft-blow-dart.typ out/draft-blow-dart.svg
typst compile --format svg draft-step-back.typ out/draft-step-back.svg
typst compile --format svg draft-revenge.typ out/draft-revenge.svg
typst compile --format svg draft-safe-for-later.typ out/draft-safe-for-later.svg
typst compile --format svg draft-repeat-action.typ out/draft-repeat-action.svg
typst compile --format svg draft-temper.typ out/draft-temper.svg
typst compile --format svg draft-flaming-arrow.typ out/draft-flaming-arrow.svg
typst compile --format svg draft-bad-meat.typ out/draft-bad-meat.svg
typst compile --format svg draft-burning-sacrifice.typ out/draft-burning-sacrifice.svg
typst compile --format svg draft-unexpected-angle.typ out/draft-unexpected-angle.svg
typst compile --format svg draft-keep-the-combo.typ out/draft-keep-the-combo.svg
typst compile --format svg draft-reach.typ out/draft-reach.svg
typst compile --format svg draft-provide-toxicity.typ out/draft-provide-toxicity.svg
typst compile --format svg draft-venomous-arrow.typ out/draft-venomous-arrow.svg
typst compile --format svg draft-thrown-shield.typ out/draft-thrown-shield.svg
typst compile --format svg draft-magic-missiles.typ out/draft-magic-missiles.svg
typst compile --format svg draft-release-steam.typ out/draft-release-steam.svg
typst compile --format svg draft-siphon.typ out/draft-siphon.svg
typst compile --format svg draft-black-hole.typ out/draft-black-hole.svg
typst compile --format svg draft-inspire.typ out/draft-inspire.svg
typst compile --format svg draft-bonfire.typ out/draft-bonfire.svg
typst compile --format svg draft-flaming-sword.typ out/draft-flaming-sword.svg
typst compile --format svg draft-envenomed-weapons.typ out/draft-envenomed-weapons.svg
typst compile --format svg draft-heat.typ out/draft-heat.svg
typst compile --format svg draft-deep-focus.typ out/draft-deep-focus.svg
typst compile --format svg draft-hook.typ out/draft-hook.svg
typst compile --format svg draft-lead.typ out/draft-lead.svg
typst compile --format svg draft-protect.typ out/draft-protect.svg
typst compile --format svg draft-spear.typ out/draft-spear.svg
typst compile --format svg draft-javelin.typ out/draft-javelin.svg
typst compile --format svg draft-jumping-attack.typ out/draft-jumping-attack.svg
typst compile --format svg draft-taunt.typ out/draft-taunt.svg
typst compile --format svg draft-combine-shoot.typ out/draft-combine-shoot.svg
typst compile --format svg draft-reflect-a-lot.typ out/draft-reflect-a-lot.svg
typst compile --format svg draft-av.typ out/draft-av.svg
typst compile --format svg draft-aim.typ out/draft-aim.svg
typst compile --format svg draft-tinder-box.typ out/draft-tinder-box.svg
typst compile --format svg draft-oil.typ out/draft-oil.svg
typst compile --format svg draft-apply-poison.typ out/draft-apply-poison.svg
typst compile --format svg draft-combine-hit.typ out/draft-combine-hit.svg
typst compile --format svg draft-combine-heal.typ out/draft-combine-heal.svg
typst compile --format svg draft-combine-defend.typ out/draft-combine-defend.svg
typst compile --format svg draft-combo-shoot.typ out/draft-combo-shoot.svg
typst compile --format svg draft-fangs.typ out/draft-fangs.svg
typst compile --format svg draft-combo-hit.typ out/draft-combo-hit.svg
typst compile --format svg draft-combo-heal.typ out/draft-combo-heal.svg
typst compile --format svg draft-combo-defend.typ out/draft-combo-defend.svg
typst compile --format svg draft-throw.typ out/draft-throw.svg
typst compile --format svg draft-salt-to-wound.typ out/draft-salt-to-wound.svg
typst compile --format pdf draft-physical.typ out/deck/digital/draft-digital.pdf
typst compile --format png draft-digital.typ out/deck/physical/draft-digital.png
typst compile --format pdf all-physical.typ out/deck/digital/all-digital.pdf
typst compile --format png all-digital.typ out/deck/physical/all-digital.png