if (-not (Test-Path "out")) {
                New-Item -ItemType Directory -Path "out" | Out-Null 
                New-Item -ItemType Directory -Path "out\deck" | Out-Null
                New-Item -ItemType Directory -Path "out\deck\digital" | Out-Null
                New-Item -ItemType Directory -Path "out\deck\physical" | Out-Null
            }
typst compile --format svg raging-bull-slash.typ out/raging-bull-slash.svg
typst compile --format svg raging-bull-right-horn.typ out/raging-bull-right-horn.svg
typst compile --format svg raging-bull-left-horn.typ out/raging-bull-left-horn.svg
typst compile --format svg raging-bull-thunderous-hooves.typ out/raging-bull-thunderous-hooves.svg
typst compile --format svg raging-bull-gore.typ out/raging-bull-gore.svg
typst compile --format svg raging-bull-gallop.typ out/raging-bull-gallop.svg
typst compile --format svg raging-bull-bull-rush.typ out/raging-bull-bull-rush.svg
typst compile --format pdf raging-bull-physical.typ out/deck/physical/raging-bull.pdf
typst compile --format png raging-bull-digital.typ out/deck/digital/raging-bull.png
typst compile --format svg raging-bull-board.typ out/raging-bull-board.svg
typst compile --format png raging-bull-board.typ out/deck/digital/raging-bull-board.png
typst compile --format svg swarm-unrelenting-hordes.typ out/swarm-unrelenting-hordes.svg
typst compile --format svg swarm-storm-of-wings.typ out/swarm-storm-of-wings.svg
typst compile --format svg swarm-back-to-the-hive.typ out/swarm-back-to-the-hive.svg
typst compile --format svg swarm-winged-doom.typ out/swarm-winged-doom.svg
typst compile --format svg swarm-gnashing-mandibles.typ out/swarm-gnashing-mandibles.svg
typst compile --format svg swarm-probing-stingers.typ out/swarm-probing-stingers.svg
typst compile --format svg swarm-tireless-drones.typ out/swarm-tireless-drones.svg
typst compile --format pdf swarm-physical.typ out/deck/physical/swarm.pdf
typst compile --format png swarm-digital.typ out/deck/digital/swarm.png
typst compile --format svg swarm-board.typ out/swarm-board.svg
typst compile --format png swarm-board.typ out/deck/digital/swarm-board.png
typst compile --format svg dragon-scorch.typ out/dragon-scorch.svg
typst compile --format svg dragon-torch.typ out/dragon-torch.svg
typst compile --format svg dragon-blasting-heat.typ out/dragon-blasting-heat.svg
typst compile --format svg dragon-cough.typ out/dragon-cough.svg
typst compile --format svg dragon-check.typ out/dragon-check.svg
typst compile --format svg dragon-mate.typ out/dragon-mate.svg
typst compile --format svg dragon-tail-swipe.typ out/dragon-tail-swipe.svg
typst compile --format svg dragon-depth-first-breath.typ out/dragon-depth-first-breath.svg
typst compile --format svg dragon-right-breath.typ out/dragon-right-breath.svg
typst compile --format svg dragon-love.typ out/dragon-love.svg
typst compile --format pdf dragon-physical.typ out/deck/physical/dragon.pdf
typst compile --format png dragon-digital.typ out/deck/digital/dragon.png
typst compile --format svg dragon-board.typ out/dragon-board.svg
typst compile --format png dragon-board.typ out/deck/digital/dragon-board.png
typst compile --format svg gardener-loot.typ out/gardener-loot.svg
typst compile --format svg gardener-twisting-vines.typ out/gardener-twisting-vines.svg
typst compile --format svg gardener-root.typ out/gardener-root.svg
typst compile --format svg gardener-toxic-spores.typ out/gardener-toxic-spores.svg
typst compile --format svg gardener-spores.typ out/gardener-spores.svg
typst compile --format svg gardener-harvest.typ out/gardener-harvest.svg
typst compile --format svg gardener-whip.typ out/gardener-whip.svg
typst compile --format svg gardener-blossom.typ out/gardener-blossom.svg
typst compile --format svg gardener-seed.typ out/gardener-seed.svg
typst compile --format pdf gardener-physical.typ out/deck/physical/gardener.pdf
typst compile --format png gardener-digital.typ out/deck/digital/gardener.png
typst compile --format svg gardener-board.typ out/gardener-board.svg
typst compile --format png gardener-board.typ out/deck/digital/gardener-board.png
typst compile --format svg golem-stalag-might.typ out/golem-stalag-might.svg
typst compile --format svg golem-groundpound.typ out/golem-groundpound.svg
typst compile --format svg golem-rock-throw.typ out/golem-rock-throw.svg
typst compile --format svg golem-cave-in.typ out/golem-cave-in.svg
typst compile --format svg golem-mud-bath.typ out/golem-mud-bath.svg
typst compile --format svg golem-stalag-tight.typ out/golem-stalag-tight.svg
typst compile --format svg golem-quake.typ out/golem-quake.svg
typst compile --format svg golem-rolling-earth.typ out/golem-rolling-earth.svg
typst compile --format svg golem-rock-blast.typ out/golem-rock-blast.svg
typst compile --format pdf golem-physical.typ out/deck/physical/golem.pdf
typst compile --format png golem-digital.typ out/deck/digital/golem.png
typst compile --format svg golem-board.typ out/golem-board.svg
typst compile --format png golem-board.typ out/deck/digital/golem-board.png
typst compile --format svg cutthroat-slash.typ out/cutthroat-slash.svg
typst compile --format svg cutthroat-coup-de-grace.typ out/cutthroat-coup-de-grace.svg
typst compile --format svg cutthroat-cloak.typ out/cutthroat-cloak.svg
typst compile --format pdf cutthroat-physical.typ out/deck/physical/cutthroat.pdf
typst compile --format png cutthroat-digital.typ out/deck/digital/cutthroat.png
typst compile --format svg cutthroat-board.typ cutthroat-board.svg
typst compile --format png cutthroat-board.typ out/deck/digital/cutthroat-board.png
typst compile --format svg ecclesiarch-heal.typ out/ecclesiarch-heal.svg
typst compile --format svg ecclesiarch-judgement.typ out/ecclesiarch-judgement.svg
typst compile --format svg ecclesiarch-dawn-to-dusk.typ out/ecclesiarch-dawn-to-dusk.svg
typst compile --format pdf ecclesiarch-physical.typ out/deck/physical/ecclesiarch.pdf
typst compile --format png ecclesiarch-digital.typ out/deck/digital/ecclesiarch.png
typst compile --format svg ecclesiarch-board.typ ecclesiarch-board.svg
typst compile --format png ecclesiarch-board.typ out/deck/digital/ecclesiarch-board.png
typst compile --format svg engine-heal.typ out/engine-heal.svg
typst compile --format svg engine-broadside.typ out/engine-broadside.svg
typst compile --format svg engine-u-turn.typ out/engine-u-turn.svg
typst compile --format pdf engine-physical.typ out/deck/physical/engine.pdf
typst compile --format png engine-digital.typ out/deck/digital/engine.png
typst compile --format svg engine-board.typ engine-board.svg
typst compile --format png engine-board.typ out/deck/digital/engine-board.png
typst compile --format svg evoker-immolation.typ out/evoker-immolation.svg
typst compile --format svg evoker-cauterize.typ out/evoker-cauterize.svg
typst compile --format svg evoker-death-ray.typ out/evoker-death-ray.svg
typst compile --format pdf evoker-physical.typ out/deck/physical/evoker.pdf
typst compile --format png evoker-digital.typ out/deck/digital/evoker.png
typst compile --format svg evoker-board.typ evoker-board.svg
typst compile --format png evoker-board.typ out/deck/digital/evoker-board.png
typst compile --format svg mystic-mystic-fog.typ out/mystic-mystic-fog.svg
typst compile --format svg mystic-harrowing-screech.typ out/mystic-harrowing-screech.svg
typst compile --format svg mystic-siphon-spirit.typ out/mystic-siphon-spirit.svg
typst compile --format pdf mystic-physical.typ out/deck/physical/mystic.pdf
typst compile --format png mystic-digital.typ out/deck/digital/mystic.png
typst compile --format svg mystic-board.typ mystic-board.svg
typst compile --format png mystic-board.typ out/deck/digital/mystic-board.png
typst compile --format svg saurian-swipe.typ out/saurian-swipe.svg
typst compile --format svg saurian-tail-whip.typ out/saurian-tail-whip.svg
typst compile --format svg saurian-toxic-spines.typ out/saurian-toxic-spines.svg
typst compile --format pdf saurian-physical.typ out/deck/physical/saurian.pdf
typst compile --format png saurian-digital.typ out/deck/digital/saurian.png
typst compile --format svg saurian-board.typ saurian-board.svg
typst compile --format png saurian-board.typ out/deck/digital/saurian-board.png
typst compile --format svg stalker-shoot.typ out/stalker-shoot.svg
typst compile --format svg stalker-shoot-n-move.typ out/stalker-shoot-n-move.svg
typst compile --format svg stalker-aim.typ out/stalker-aim.svg
typst compile --format pdf stalker-physical.typ out/deck/physical/stalker.pdf
typst compile --format png stalker-digital.typ out/deck/digital/stalker.png
typst compile --format svg stalker-board.typ stalker-board.svg
typst compile --format png stalker-board.typ out/deck/digital/stalker-board.png
typst compile --format svg vanguard-armor-shatter.typ out/vanguard-armor-shatter.svg
typst compile --format svg vanguard-sword-and-board.typ out/vanguard-sword-and-board.svg
typst compile --format svg vanguard-exertion.typ out/vanguard-exertion.svg
typst compile --format pdf vanguard-physical.typ out/deck/physical/vanguard.pdf
typst compile --format png vanguard-digital.typ out/deck/digital/vanguard.png
typst compile --format svg vanguard-board.typ vanguard-board.svg
typst compile --format png vanguard-board.typ out/deck/digital/vanguard-board.png
typst compile --format svg draft-fire-walk.typ out/draft-fire-walk.svg
typst compile --format svg draft-poisonous-cloud.typ out/draft-poisonous-cloud.svg
typst compile --format svg draft-restore.typ out/draft-restore.svg
typst compile --format svg draft-throw.typ out/draft-throw.svg
typst compile --format svg draft-smoke-bombs.typ out/draft-smoke-bombs.svg
typst compile --format svg draft-retaliate.typ out/draft-retaliate.svg
typst compile --format svg draft-evasive-maneuvers.typ out/draft-evasive-maneuvers.svg
typst compile --format svg draft-tinder-box.typ out/draft-tinder-box.svg
typst compile --format svg draft-blood-magic.typ out/draft-blood-magic.svg
typst compile --format svg draft-apply-poison.typ out/draft-apply-poison.svg
typst compile --format svg draft-leap-frog.typ out/draft-leap-frog.svg
typst compile --format svg draft-flee.typ out/draft-flee.svg
typst compile --format svg draft-shadows-of-doubt.typ out/draft-shadows-of-doubt.svg
typst compile --format svg draft-hook.typ out/draft-hook.svg
typst compile --format svg draft-lead.typ out/draft-lead.svg
typst compile --format svg draft-death-from-above.typ out/draft-death-from-above.svg
typst compile --format svg draft-blowdart.typ out/draft-blowdart.svg
typst compile --format svg draft-weakpoint.typ out/draft-weakpoint.svg
typst compile --format svg draft-flaming-arrow.typ out/draft-flaming-arrow.svg
typst compile --format svg draft-venomous-arrow.typ out/draft-venomous-arrow.svg
typst compile --format svg draft-thrown-shield.typ out/draft-thrown-shield.svg
typst compile --format svg draft-unexpected-angle.typ out/draft-unexpected-angle.svg
typst compile --format svg draft-loose.typ out/draft-loose.svg
typst compile --format svg draft-step-back.typ out/draft-step-back.svg
typst compile --format svg draft-revenge.typ out/draft-revenge.svg
typst compile --format svg draft-flaming-sword.typ out/draft-flaming-sword.svg
typst compile --format svg draft-spear.typ out/draft-spear.svg
typst compile --format svg draft-javelin.typ out/draft-javelin.svg
typst compile --format svg draft-fangs.typ out/draft-fangs.svg
typst compile --format svg draft-salt-to-wound.typ out/draft-salt-to-wound.svg
typst compile --format svg draft-siphon.typ out/draft-siphon.svg
typst compile --format svg draft-magic-missiles.typ out/draft-magic-missiles.svg
typst compile --format svg draft-fan-of-knives.typ out/draft-fan-of-knives.svg
typst compile --format svg draft-bad-meat.typ out/draft-bad-meat.svg
typst compile --format svg draft-delay.typ out/draft-delay.svg
typst compile --format svg draft-save-for-later.typ out/draft-save-for-later.svg
typst compile --format svg draft-deja-vu.typ out/draft-deja-vu.svg
typst compile --format svg draft-meditate.typ out/draft-meditate.svg
typst compile --format svg draft-deep-focus.typ out/draft-deep-focus.svg
typst compile --format svg draft-protect.typ out/draft-protect.svg
typst compile --format svg draft-taunt.typ out/draft-taunt.svg
typst compile --format svg draft-absorb-pain.typ out/draft-absorb-pain.svg
typst compile --format svg draft-light-in-the-dark.typ out/draft-light-in-the-dark.svg
typst compile --format svg draft-balance-the-scales.typ out/draft-balance-the-scales.svg
typst compile --format svg draft-burning-effigy.typ out/draft-burning-effigy.svg
typst compile --format svg draft-provide-toxicity.typ out/draft-provide-toxicity.svg
typst compile --format svg draft-inspire.typ out/draft-inspire.svg
typst compile --format svg draft-envenomed-weapons.typ out/draft-envenomed-weapons.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format svg draft-move.typ out/draft-move.svg
typst compile --format pdf draft-physical.typ out/deck/physical/draft.pdf
typst compile --format png draft-digital.typ out/deck/digital/draft.png
typst compile --format svg raging-bull-leyline.typ out/raging-bull-leyline.svg
typst compile --format png raging-bull-leyline.typ out/raging-bull-leyline.png
typst compile --format svg swarm-leyline.typ out/swarm-leyline.svg
typst compile --format png swarm-leyline.typ out/swarm-leyline.png
typst compile --format svg dragon-leyline.typ out/dragon-leyline.svg
typst compile --format png dragon-leyline.typ out/dragon-leyline.png
typst compile --format svg gardener-leyline.typ out/gardener-leyline.svg
typst compile --format png gardener-leyline.typ out/gardener-leyline.png
typst compile --format svg golem-leyline.typ out/golem-leyline.svg
typst compile --format png golem-leyline.typ out/golem-leyline.png
typst compile --format pdf leylinedeck-physical.typ out/deck/physical/leylinedeck.pdf
typst compile --format png leylinedeck-digital.typ out/deck/digital/leylinedeck.png
typst compile --format svg trigger-TwoReds.typ out/trigger-TwoReds.svg
typst compile --format png trigger-TwoReds.typ out/trigger-TwoReds.png
typst compile --format svg trigger-TwoBlues.typ out/trigger-TwoBlues.svg
typst compile --format png trigger-TwoBlues.typ out/trigger-TwoBlues.png
typst compile --format svg trigger-TwoGreens.typ out/trigger-TwoGreens.svg
typst compile --format png trigger-TwoGreens.typ out/trigger-TwoGreens.png
typst compile --format svg trigger-NoMoves.typ out/trigger-NoMoves.svg
typst compile --format png trigger-NoMoves.typ out/trigger-NoMoves.png
typst compile --format svg trigger-Corners.typ out/trigger-Corners.svg
typst compile --format png trigger-Corners.typ out/trigger-Corners.png
typst compile --format svg trigger-Center.typ out/trigger-Center.svg
typst compile --format png trigger-Center.typ out/trigger-Center.png
typst compile --format svg trigger-TenDamage.typ out/trigger-TenDamage.svg
typst compile --format png trigger-TenDamage.typ out/trigger-TenDamage.png
typst compile --format svg trigger-FiveHits.typ out/trigger-FiveHits.svg
typst compile --format png trigger-FiveHits.typ out/trigger-FiveHits.png
typst compile --format svg trigger-TenCards.typ out/trigger-TenCards.svg
typst compile --format png trigger-TenCards.typ out/trigger-TenCards.png